### ISSUE TITLE
Thanks for using PyNutshell library

### ISSUE THREAD

**Issue by KrishnanSG** [Gaurav-71/UNA-Unisys-Natural-Assistant#1]
Hi @Gaurav-71 @weirdscorpio 

 I'm Krishnan S G, creator of [PyNutshell](https://github.com/KrishnanSG/nutshell) library.

Glad that you found PyNutshell interesting and considered using it in our project.

Would love to hear more from you guys.
Cheers! 😀

**Comment by Gaurav-71** [comment]
Hi Krishna,

The library was very useful and aided my team and i to improve a
summarization feature in our project,

Regards,
Gaurav V & Team
